# Generated by Django 4.2.1 on 2023-07-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_base64_string',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
